### ISSUE TITLE
Accept urls from STDIN [Feature]

### ISSUE THREAD

**Issue by uBadRequest** [FlameOfIgnis/puff#5]
Could you add the ability to pipe a list of urls into puff?

**Comment by uBadRequest** [comment]
For now ill just use a while loop :)

**Comment by ignis-sec** [comment]
I really like this idea, and i'll start working on this as soon as i can :)

**Comment by ignis-sec** [comment]
I hope this is what you had in mind too!

> **Running with stdin fuzzing mode:**
> ```
> cat urls.txt | node puff.js -w .\wordlist-examples\events.txt
> 
> 
> cat urls.txt | puff -w .\wordlist-examples\events.txt
> ```
> Where urls.txt is
> ```
> http://example.com?query=FUZZ
> https://another.com/page/#FUZZ
> ```
> 
> 
> **Running with stdin single payload mode:**
> ```
> cat urls.txt | node puff.js
> 
> 
> cat urls.txt | puff
> ```
> 
> Where urls.txt is
> ```
> http://example.com?query=<script>alert()</script>
> http://example.com?query=javascript:alert()
> https://another.com/page/#<script>alert()</script>
> ```
>
